language: go

go:
  - 1.x

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go get -v ./...
  - export GOPATH=$(pwd)
  - gox -os="linux darwin" -arch="amd64" -output="cli.." -verbose ./...
  - ls -lrt
