language: go

go:
  - 1.12.5

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip
  
addons:
  sonarcloud:
    organization: "atselvan"
    token:
      secure: "ll3CnSUgYoOTo6T5iiB//Pw631mRxNYYiaBR4V8Mp6BFesIue4IRI3OCoFJ/YLH7NeehLmx11Fet4MuyyJcn56Woay0b+C4Ljp400SO/f7iEj5lRiVpjlRySJYR6QbY92D3MhYnN3ZuVCinTZylAUx3UN+O8sWuyQI4t492YDYdq48C1G64yXLa77nRdU6PHW/DK5MmsVcOjzEM53wiDpUh7zWY+UM2ZyK9LH/6qXPV2ukHG7c6SEGXuQyOmAVv6PrrI5HpyKxTZdjWWvVxjLnbJSgkKl/H2sjG+a3KoI6v20wvRtkMsdhDA/us7jmupdTyfdFl/Yzj4+l4H0+V6iNzAUzbo363YHwXNU5hK7LJ4GmmWQ5J2k8dX0zj63NBb/sGmewcnz690y/VLRHwFtnuR9VScIr6a7yNHSmqYcDG2P5EtK7PGxpcgb+6slFxLBTnNLijFpZsovvkuK/qnFSpLuOK7nd2jzJtrIBR/VSBae1nhvlV3Cjdyu38C1y/CjLrTcPFuLSQmazdDsVE2YaNXpc4xPcQ5vcfy+F3A6Ateu2Y1hNdoJxcjiZ+0Qdl2vShOgKpJMQAHiOrjtSx/n09LX1wKvlJzn+YvrMcOVJwQNqiGcA32vFVF/oVY4V+HSHCkjRs0z6SDSii5XRFFM+mAuiMe96qEAVVzCJPAKU8="

script:
  - export GOPATH=$(pwd)
  - cd src/com/privatesquare/go/nexus3-repository-cli/
  - go get -v ./...
  - gox -os="linux darwin" -arch="amd64" -verbose ./...
  - ls -lrt
  - sonar-scanner -X
  
notifications:
  email: false
